---

- name: eHanse User Konfigurieren
  hosts: eHanse
  remote_user: joerg
  

  #default variables - passw generieren mit mkpasswd --method=sha-512
  vars_files:
    - group_vars/vars 
    - group_vars/vault

  vars:
    ehanse_users:
    - username: joerg
      pwd_cryp: "{{ joerg_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/joerg.pub') }}"  
    - username: frank
      pwd_cryp: "{{ frank_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/frank.pub') }}"   
    - username: dominik
      pwd_cryp: "{{ dominik_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/dominik.pub') }}"
 


  #handlers
  

  #meta


  #tasks 
  tasks:
   - name: Gruppe sshusers einrichten
     group:
       name: sshusers
       state: present

   - name: users einrichten
     user:  
       name: "{{ item.username }}"
       password: "{{ item.pwd_cryp }}" 
       createhome: yes
       home: "/home/{{ item.username }}"
       shell: /bin/bash
       system: no
       groups: sshusers,sudo
       state: present
     with_items:
       - "{{ ehanse_users }}"

   - name: authorized_keys einrichten
     authorized_key:
       user: "{{ item.username }}"   
       key: "{{ item.key }}"
     with_items:
       - "{{ ehanse_users }}" 
      
   - name: User entfernen (Beispiel)
     user:
       name: irgendeinuser
       state: absent
       remove: yes
       force: yes 
