# Dieses Playbook MUSS mit Python2 als ansible_interpreter
# ausgeführt werden! Also den command
#   ansible_python_interpreter=/usr/bin/python3
# im Inventory file weglassen! Ansonsten schlägt die Installation
# von psycopg2 (Python-Postgres-Adapter) fehl.

---
- name: Odoo installieren,
  vars_files:  # Verweis auf verschlüsselte Pws
    - vars
    - vault
  hosts: all
  vars: []
  pre_tasks:
    - apt:
       name: "{{ item }}"
       update_cache: no
       state: present
      loop:
       - python3-pip            #vorab pip3 installieren
       - python-pip
       - postgresql             #vorab postgreql installieren
       - ttf-wqy-zenhei         #vorab chinesische Schrift installieren
       - ttf-wqy-microhei       #vorab chinesische Schrift installieren
       - python-setuptools
       - python3-setuptools
    - pip:
       name: XlsxWriter         # as per request by Manfred
       state: latest

    - locale_gen:
       name: de_DE.UTF-8
       state: present
    - locale_gen:
       name: en_US.UTF-8
       state: present
  roles:
   - ansible-odoo
  post_tasks:
   - git:
       repo: 'https://github.com/eHanse-IT/OAW_custom.git'
       dest: '/home/odoo/odoo/custom/OAW-custom'
       force: yes
       umask: '755'
   - git:
       repo: 'https://github.com/rfhk/awo-custom.git'
       dest: '/home/odoo/odoo/custom/awo-custom'
       force: yes
       umask: '755'
   - file:
       path: '/home/odoo/odoo/custom/'
       owner: "{{ odoo_user }}"
       group: "{{ odoo_user }}"
       mode: 0755
       recurse: yes



