---
- name: User konfigurieren
  hosts: eHanse
  vars_files:  # Verweis auf verschlüsselte Pws
    - vars
    - vault
  vars:
    ehanse_users:
    - username: joerg
      pwd_cryp: "{{ joerg_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/joerg.pub') }}"
    - username: frank
      pwd_cryp: "{{ frank_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/frank.pub') }}"
    - username: dominik
      pwd_cryp: "{{ dominik_pwd_cryp }}"
      key: "{{ lookup('file', 'roles/users/authorized_keys/dominik.pub') }}"
  roles:
   - users


- name: SSH konfigurieren
  hosts: eHanse
  vars:
    ssh_soll_port: "{{ ansible_port }}"
  roles:
   - ssh



- name: Firewall konfigurieren
  hosts: eHanse
  vars:
    ufw_ipv6: "yes"
    ufw_default_input_policy: "DROP"
    ufw_default_output_policy: "ACCEPT"
    ufw_default_forward_policy: "DROP"
    ufw_default_application_policy: "SKIP"
  roles:
   - firewall

- name: Apache konfigurieren
  hosts: eHanse
  #vars:
  # apache_listen_port
  # apache_listen_ssl
  # apache_vhosts:
  #  - vhost_servername: wiki.ehanse.de
  #    vhost_domain: ...
  #    vhost_documentroot: ...
  #    vhost_SSL Certific: ...
  #
  #
  #
  #
  roles:
   - apache



 # timezone
 # hostnbame
 # odoo --> OCA odoo ansible script


  




       



