---

 # Verweise auf andere Playbooks (einfaches Konfigschema)
 - include: pb_users.yml
 - include: pb_ssh.yml
 - include: pb_firewall.yml



 # Verweise auf echte Ansible-Roles
# - hosts: eHanse
#   user: joerg
#   roles:
#     -role: letsencrypt
#      letsencrpyt-variable: bla


 # apache
 # timezone
 # hostnbame
 # odoo --> schenkels script


  




       



