---
- name: Apache konfigurieren
  vars_files:  # Verweis auf verschlüsselte Pws
    - vars
    - vault
  hosts: all
  vars:
    apache_listen_port: 80
    apache_listen_ssl: 443
  roles:
   - apache

- name: Certbot fuer LetsEncrypt Zertifikate
  vars_files:  # Verweis auf verschlüsselte Pws
    - vars
    - vault
  hosts: ehanse

  roles:
   - certbot