---
- name: SSH, Users, sysctl.conf, git konfigurieren, Sys updaten
  hosts: all
  vars_files:  # Verweis auf Ziel Ansible Port im Vault
    - vars
    - vault
  roles:
   - ssh
   - hostname
   - timezone
   - users
   - sysctl
   - git

- name: Zum Schluss die Firewall konfigurieren
  hosts: all
  vars_files:  # Verweis auf Ziel Ansible Port im Vault
    - vars
    - vault
  roles:
   - firewall