---
# Dieses Playbook dient zur initialen, sicheren Konfiguration eines Servers.
#
#

- name: Essentials - Sysctl.conf, Firewall, Git, Python, Apt-Update
  hosts: all
  vars_files:
    - vars
    - vault
  - name: update and upgrade apt.
    apt:
      update_cache: yes
      upgrade: full
      autoclean: yes
      autoremove: yes
  - name: manually set 'gather facts' back 'on' again
    setup:
    tags: python
  - name: Locales installieren (de_DE und en_US)
    locale_gen:
      name: "{{ item }}"
      state: present
    loop:
    - de_DE.UTF-8
    - en_US.UTF-8
  roles:
   - hostname
   - timezone
   - sysctl
   - git
   - firewall
   - unattended-upgrades
   # enable pipelining