# Dieses Playbook installiert Lets Encrypt Zertifikate auf allen übergebenen Domains.
# Es sollte als letztes ausgeführt werden, damit alle Services, die vom Web aus
# erreicht werden sollen, bereits einen VHost im Apache haben.
#


- name: Certbot fuer LetsEncrypt Zertifikate
  hosts: all
  vars_files:  # Verweis auf verschlüsselte Pws
    - vars
    - vault
  roles:
   - certbot

   ## TODO:
   #folgende Fehlermeldung auf frischen Servern im check mode muss gehandelt werden: python-apt must be installed to use check mode. If run normally this module can auto-install it."}
