---
# Verweise auf andere Playbooks (einfaches Konfigschema)
- include: pb_users.yml


# Verweise auf echte Ansible-Roles
- hosts:  eHanse
  roles:
   - role: ssh


- hosts: eHanse
  user: joerg
  roles:
   - role: firewall
   - role: apache







 # timezone
 # hostnbame
 # odoo --> schenkels script


  




       



