---
- name: Kreiere Odoo vHost in Apache.
  template:
    src: templates/odoohost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ odoo_domains }}"

- name: Symlink neuen VHost nach sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item }}.conf"
    state: link
  with_items:
    - "{{ odoo_domains }}"
  notify: restart_apache2_event

#   # finally, make sure Odoo is running fine on the target machine (no "internal web server error")
#- name: Teste ob Odoo ueber den kreierten vHost erreichbar ist
#  uri:
#    url: https://{{ domain }}
#    status_code: 200
#    ignore_errors: yes





