---

- name: eHanse User Konfigurieren
  hosts: eHanse
  remote_user: joerg
  

  #default variables - passw generieren mit mkpasswd --method=sha-512
  vars:
    ehanse_users:
    - username: joerg
      pwd_cryp: '$6$orQVPJDyOhG$SKNJNONgf9jPtkMpJg1YE1tizTMnG7vCTgxd7VtX9MoJAqlMbLXQfKNdYPyn8WT/behsml65UJzBwP1iH4lnc1'
      key: "{{ lookup('file', 'authorized_keys/joerg.pub') }}"  
    - username: frank
      pwd_cryp: '$6$50IEJs25URBMSfc$f5WYJveFe2LSR6QNx17v1D35k.mvNby.MWq0xzHGxOaIFVmoaId9EpvXa4T3Y0X2smZzZLwkYgYyv6G5vre7M0'
      key: "{{ lookup('file', 'authorized_keys/frank.pub') }}"   
    - username: dominik
      pwd_cryp: '$6$gM3XXer2j$9Ticvw/6tWkLXhG6wnloZSexv6E82U7fFfI7akhjY8iW0gg64CYmdqoR7nnrc.HfMqAPlKTh67alQU66X7Cj0.'
      key: "{{ lookup('file', 'authorized_keys/dominik.pub') }}"  


  #handlers
  

  #meta


  #tasks 
  tasks:
   - name: Gruppe sshusers einrichten
     group:
       name: sshusers
       state: present

   - name: users einrichten
     user:  
       name: "{{ item.username }}"
       password: "{{ item.pwd_cryp }}" 
       createhome: yes
       home: "/home/{{ item.username }}"
       shell: /bin/bash
       system: no
       groups: sshusers,sudo
       state: present
     with_items:
       - "{{ ehanse_users }}"

   - name: authorized_keys einrichten
     authorized_key:
       user: "{{ item.username }}"   
       key: "{{ item.key }}"
     with_items:
       - "{{ ehanse_users }}" 
      
   - name: User entfernen (Beispiel)
     user:
       name: irgendeinuser
       state: absent
       remove: yes
       force: yes 
