---
- name: keine Fakten sammeln
  set_fact:
    gather_facts: false
    ssh_soll_port: "{{ host_port }}"

- name: Test SSH auf Port {{ ansible_port }} erreichbar
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "7"
  register: custom_ssh
  check_mode: no  #always run active, even if not in check mode
  ignore_errors: yes

- name: Wenn SSH Soll-Port {{ host_port }} closed, ueberschreibe ansible_port und setze 22
  set_fact:
    ansible_port: "22"
  when: custom_ssh.state is defined and
        custom_ssh.state != "started"

- name: Nach Portfindung einen kurzen Ping um zu checken dass die Verbindung funzt
  ping:

- name: sshd_config uebernehmen
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh_event