---

- name: keine Fakten sammeln
  set_fact:
    gather_facts: false

- name: Test SSH auf Soll-port {{ ansible_port }} erreichbar
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "7"
  register: custom_ssh
  ignore_errors: yes

- name: Wenn SSH Soll-Port {{ ansible_port }} closed, ueberschreibe ansible_port und setze 22
  set_fact:
    ansible_port: "22"
  when: custom_ssh is defined and
        custom_ssh.state != "started"

- name: Nach Portfindung einen kurzen Ping um zu checken dass die Verbindung funzt
  ping:

- name: sshd_config - SSH port einstellen
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ ssh_soll_port }}"
  notify: restart_ssh_event

- name: sshd_config - SSH nicht für root zulassen
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart_ssh_event

- name: sshd_config - SSH nur mit keyfiles und ohne Passwort
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart_ssh_event

- name: sshd_config - SSH nur fuer Gruppen sshlogin und sshusers
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^AllowGroups'
    line: 'AllowGroups sshusers sshlogin'
  notify: restart_ssh_event