---
- name: sshd_config uebernehmen
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s    # checks that the file will work
  notify: restart_ssh_event