# handlers file for fail2ban
---
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'

