---
# Download and install the barcode fonts from ReportLab
- name: Create the font directory
  file: path="/home/{{ odoo_user }}/odoo/fonts" state=directory


- name: Download the ReportLab barcode fonts
  get_url: url="{{ odoo_reportlab_font_url }}"
           dest="/home/{{ odoo_user }}/pfbfer.zip"


- name: Install unzip
  apt: name=unzip state=present

- name: Unzip the ReportLab fonts
  unarchive: src="/home/{{ odoo_user }}/pfbfer.zip"
             dest="/home/{{ odoo_user }}/odoo/fonts"
             owner={{ odoo_user }}
             group={{ odoo_user }}
             mode="u=rwX,go=rX"
             copy=No
             creates="/home/{{ odoo_user }}/odoo/fonts/_abi____.pfb"
